# Generated by Django 2.1.15 on 2020-05-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0006_auto_20200502_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
