# Generated by Django 2.1.15 on 2020-05-01 19:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='photos/default.jpg', upload_to=accounts.models.Profile.rename_file),
        ),
    ]
