# Generated by Django 2.1.15 on 2020-05-02 14:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200502_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='photos/default.jpg', upload_to=accounts.models.Profile.rename_file),
        ),
    ]
